<?php

return [
    [
        'name' => "Appartamento Rosso",
        'price' => 79,
        'rooms' => 4,
        'beds' => 6,
        'bathrooms' => 2,
        'square_meters' => 30,
        'address' => "via Giuseppe Garibaldi 4, 39100, Bolzano",
        'thumb' => "https://a0.muscache.com/im/pictures/2e7da028-cfb2-41a4-aaa3-46fbb715ef61.jpg?im_w=1200",
        'description' => "L'appartamento di circa 28mq al secondo piano è adatto per 2 persone. Si compone di una camera matrimoniale o soggiorno, una piccola cucina separata e bagno. La cucina ha un angolo cottura con fornelli, forno a microonde, lavastoviglie e frigorifero. Macchina per il caffè, bollitore, pentole, pentole, bicchieri, piatti, posate e altri utensili da cucina sono disponibili. Il bagno ha una doccia, wc e lavandino. Nell'appartamento c'è anche una TV con canali italiani e tedeschi, oltre a Internet.
        Lenzuola e asciugamani, così come asciugamani da cucina sono inclusi. Il prezzo indicato è per 2 persone.",

    ],
    [
        'name' => "Il Monolocale",
        'price' => 75,
        'rooms' => 2,
        'beds' => 3,
        'bathrooms' => 1,
        'square_meters' => 20,
        'address' => "via Alto Adige 2, 39100, Bolzano",
        'thumb' => "https://a0.muscache.com/im/pictures/miso/Hosting-704718551122371442/original/1e8515b7-6d59-4c1d-828f-eb6f0255786e.jpeg?im_w=1200",
        'description' => "Ai piedi di Castel Firmiano (Messner Mountain Museum), tra i meleti, con accesso diretto ai sentieri escursionistici e ciclabili, si trova l'area ricreativa esterna di Kaiserau.
        Qui potrete scegliere tra una gita sulla strada del vino, sulle Dolomiti, sui laghi di montagna, una sciata e di più.",

    ],
    [
        'name' => "Villa dei Fiori",
        'price' => 90,
        'rooms' => 2,
        'beds' => 3,
        'bathrooms' => 1,
        'square_meters' => 20,
        'address' => "via Argentieri 17, 39100, Bolzano",
        'thumb' => "https://a0.muscache.com/im/pictures/52808e2b-5b1c-4e3c-be89-a80e81e9714a.jpg?im_w=1200",
        'description' => "Appartamento bilocale appena rinnovato in centro...5 minuti a piedi da piazza Walther con il Duomo e centro storico, composto da zona giorno con cucina attrezzata di lavastoviglie piastre induzione, forno, macchina caffè espresso, bollitore , soggiorno con tv led 43 pollici e zona pranzo, camera da letto antibagno e bagno. Router modem Vodafone portatile. Box auto nel piano interrato con ascensore ( 12 euro al giorno su richiesta) e pulizie finali 35 euro da saldarsi in contanti all'arrivo.",

    ],
    [
        'name' => "Villa di Campagna",
        'price' => 120,
        'rooms' => 2,
        'beds' => 5,
        'bathrooms' => 3,
        'square_meters' => 29,
        'address' => "via Dei Bottai 2, 39100, Bolzano",
        'thumb' => "https://mondoversilia.it/wp-content/uploads/2021/08/Villa-in-vendita-nella-campagna-di-Pietrasanta-Cod-1015-02.jpg",
        'description' => "",

    ],
    [
        'name' => "Casa Rosa",
        'price' => 87,
        'rooms' => 3,
        'beds' => 4,
        'bathrooms' => 1,
        'square_meters' => 34,
        'address' => "via Brennero, 39100, Bolzano",
        'thumb' => "https://a0.muscache.com/im/pictures/miso/Hosting-619440242279649568/original/b929a104-ea44-4cf8-8c58-5b2d45f4b374.jpeg?im_w=1200",
        'description' => "Vieni a soggiornare nel nostro bellissimo appartamento su BnB! Lasciati incantare dall'atmosfera accogliente e confortevole che troverai non appena varcherai la soglia. L'appartamento è dotato di tutti i comfort necessari per un soggiorno indimenticabile e la sua posizione centralissima ti permetterà di esplorare la città in tutta comodità. Non perdere l'occasione di vivere un'esperienza unica e prenota subito il tuo soggiorno!.",

    ],
    [
        'name' => "Il Nido",
        'price' => 90,
        'rooms' => 2,
        'beds' => 1,
        'bathrooms' => 1,
        'square_meters' => 25,
        'address' => "via del Calvario 4, 39100, Bolzano",
        'thumb' => "https://a0.muscache.com/im/pictures/miso/Hosting-765166979913672752/original/0da9f863-2b1c-4414-b401-8677339bc876.jpeg?im_w=1200",
        'description' => "Vuoi vivere una vacanza da favola? Il nostro appartamento su BnB ti aspetta! Con i suoi interni raffinati e l'atmosfera romantica, è la scelta perfetta per una fuga d'amore o una vacanza di relax in compagnia. Non lasciartelo sfuggire!",

    ],
    [
        'name' => "Villetta in Campagna",
        'price' => 82,
        'rooms' => 4,
        'beds' => 4,
        'bathrooms' => 1,
        'square_meters' => 28,
        'address' => "via dei Cappuccini 12, 39100, Bolzano",
        'thumb' => "https://www.modenatoday.it/~media/horizontal-hi/23116798187852/villaemma-2.jpg",
        'description' => "Se stai cercando un alloggio centrale ed economico, il nostro appartamento su BnB è la scelta ideale! Con la sua posizione strategica, potrai raggiungere a piedi i principali luoghi di interesse della città senza spendere una fortuna.",

    ],
    [
        'name' => "Appartamento Blu",
        'price' => 105,
        'rooms' => 1,
        'beds' => 2,
        'bathrooms' => 1,
        'square_meters' => 28,
        'address' => "via Cavour 6, 39100, Bolzano",
        'thumb' => "https://a0.muscache.com/im/pictures/2ac5d6b9-fc7a-4e45-9435-916fd1ddd59e.jpg?im_w=1200",
        'description' => "Scegli il nostro appartamento su BnB per una vacanza rilassante e confortevole. Goditi la pace e la tranquillità della sua posizione isolata, immersa nella natura, senza rinunciare ai comfort moderni come la connessione Wi-Fi e la TV satellitare.",

    ],
    [
        'name' => "Casa dei Sogni",
        'price' => 144,
        'rooms' => 1,
        'beds' => 1,
        'bathrooms' => 1,
        'square_meters' => 40,
        'address' => "via Dante, 39100, Bolzano",
        'thumb' => "https://a0.muscache.com/im/pictures/99420083/63792fcb_original.jpg?im_w=720",
        'description' => "L'attico India è composto da un'ampia camera da letto dotata di letto a due piazze matrimoniale, cassettone guardaroba, e finestra che guarda sul cortile. La cucina dispone di un ampio bancone con piano cottura, lavatrice, divano e accesso alla terrazzina. L'anti bagno precede il bagno dotato di vasca.",

    ],
    [
        'name' => "La Casetta",
        'price' => 54,
        'rooms' => 1,
        'beds' => 2,
        'bathrooms' => 1,
        'square_meters' => 20,
        'address' => "Via Molini 7, 39100, Bolzano",
        'thumb' => "https://a0.muscache.com/im/pictures/miso/Hosting-52067293/original/0e7dd49d-f4a6-47b1-94f9-3be3c8d33c4f.jpeg?im_w=1200",
        'description' => "Appartamento per 2-3 persone, recentemente ristrutturato in zona panoramica e soleggiata (il centro è tranquillamente raggiungibile a piedi in 5-10 minuti) con camera matrimoniale.",

    ],
    [
        'name' => "Villa con Piscina",
        'price' => 16,
        'rooms' => 3,
        'beds' => 2,
        'bathrooms' => 1,
        'square_meters' => 40,
        'address' => "Via San Lorenzo 5, 73048, Nardò",
        'thumb' => "https://txc5xc6e.cdn.imgeng.in/custom/01505/foto/20211112102212-47.jpg",
        'description' => "si tratta di una camera matrimoniale ampia  (40mq) con la possibilità di un terzo letto, arredata con stile e confort. 
        la stanza fa parte di una casa antica, con spazi condivisi tra cui un ampia cucina,  wifi, un giardino di 100 mq arredato.",

    ],
    [
        'name' => "Appartamento Giallo",
        'price' => 130,
        'rooms' => 4,
        'beds' => 4,
        'bathrooms' => 1,
        'square_meters' => 200,
        'address' => "Via barletta 32, 73048, Nardò",
        'thumb' => "https://sulbric.com/wp-content/uploads/2018/07/DSC_0490_edit.jpg",
        'description' => "si tratta di una camera matrimoniale ampia  (40mq) con la possibilità di un terzo letto, arredata con stile e confort. 
        la stanza fa parte di una casa antica, con spazi condivisi tra cui un ampia cucina,  wifi, un giardino di 100 mq arredato.",

    ],
    [
        'name' => "Casa sul Lago",
        'price' => 98,
        'rooms' => 3,
        'beds' => 5,
        'bathrooms' => 1,
        'square_meters' => 70,
        'address' => "Via Guicciardini 41, 50125, Firenze FI",
        'thumb' => "https://cdn2.hometogo.net/small/v1/157/2d0/08652a3e130b60fc95c6304a58.jpg",
        'description' => "L'appartamento si trova nel cuore di Firenze, a pochi passi dal centro storico. Dispone di tre camere da letto, un bagno, una cucina attrezzata e un soggiorno con vista panoramica sulla città. Ideale per famiglie o gruppi di amici.",

    ],
    [
        'name' => "Loft Moderno",
        'price' => 85,
        'rooms' => 2,
        'beds' => 3,
        'bathrooms' => 1,
        'square_meters' => 45,
        'address' => "Via del Governo Vecchio 70, 00186, Roma RM",
        'thumb' => "https://www.marazzi.it/media/filer_public_thumbnails/filer_public/88/d1/88d153ae-72b4-4773-8040-ffa6af1fcf57/marazzi_loft-gaggiano_016_main.jpg__1190x600_q85_crop_subsampling-2.jpg",
        'description' => "Luminoso appartamento nel cuore di Roma, a due passi da Piazza Navona e dal Pantheon. Composto da un soggiorno con divano letto, una camera matrimoniale, una cucina attrezzata e un bagno. Perfetto per una coppia o una piccola famiglia.",

    ],
    [
        'name' => "Casa in Collina",
        'price' => 75,
        'rooms' => 2,
        'beds' => 4,
        'bathrooms' => 1,
        'square_meters' => 50,
        'address' => "Via Giuseppe Giusti 16, 50121, Firenze FI",
        'thumb' => "https://st.hzcdn.com/simgs/pictures/facciate-di-case/casa-in-collina-gianfranco-sangalli-architetti-img~2f811a58061fab00_4-4542-1-bc40c3e.jpg",
        'description' => "Accogliente appartamento nel quartiere di Santa Croce, a pochi minuti a piedi dal centro storico di Firenze. Dispone di una camera matrimoniale, una camera doppia, una cucina attrezzata e un bagno. Ideale per famiglie o gruppi di amici.",

    ],
    [
        'name' => "Il Rifugio",
        'price' => 120,
        'rooms' => 3,
        'beds' => 6,
        'bathrooms' => 2,
        'square_meters' => 90,
        'address' => "Via dell'Umiltà 39, 00187, Roma RM",
        'thumb' => "https://www.lapassionediarredare.it/wp-content/uploads/2020/12/Appartamento-di-100-mq-4.jpg",
        'description' => "Elegante appartamento nel cuore di Roma, a pochi passi dalla Fontana di Trevi e dal Colosseo."
    ],
    [
        'name' => "Appartamento al Mare",
        'price' => 65,
        'rooms' => 1,
        'beds' => 2,
        'bathrooms' => 1,
        'square_meters' => 25,
        'address' => "Via San Giovanni 25, 00186, Roma RM",
        'thumb' => "https://media.karousell.com/media/photos/products/2022/8/23/freehold_township_property_in__1661254509_47ba0098_progressive",
        'description' => "A 5 minuti a piedi dal Colosseo, accogliente monolocale nel cuore di Roma. Dotato di cucina attrezzata, bagno privato, aria condizionata e connessione Wi-Fi gratuita. Luminoso e silenzioso con vista sui tetti della città. Ideale per coppie o singoli viaggiatori.",
    ],

    [
        'name' => "Casa Rustica",
        'price' => 110,
        'rooms' => 3,
        'beds' => 5,
        'bathrooms' => 2,
        'square_meters' => 80,
        'address' => "Via degli Artisti 12, 50132, Firenze FI",
        'thumb' => "https://images.homify.com/c_fill,f_auto,q_0,w_740/v1442925714/p/photo/image/928501/_DSC2118.jpg",
        'description' => "Appartamento recentemente ristrutturato in un palazzo storico del centro di Firenze, vicino alla stazione Santa Maria Novella. Composto da tre camere da letto, due bagni, salotto con angolo cottura e balcone. Arredato con gusto e dotato di ogni comfort.",
    ],

    [
        'name' => "Villa degli Ulivi",
        'price' => 80,
        'rooms' => 2,
        'beds' => 4,
        'bathrooms' => 1,
        'square_meters' => 50,
        'address' => "Via di Mezzo 6, 53100, Siena SI",
        'thumb' => "https://www.holidaycasa.it/affitti/fotos/2/15641506370f5b73286b8fbc5d1187802d026dc07a/15641507689002e689c71e082f093bd724f8888126.jpg",
        'description' => "Grazioso appartamento nel centro storico di Siena, a pochi passi dalla Piazza del Campo. Composto da due camere da letto, soggiorno con angolo cottura, bagno e terrazza panoramica con vista sulla città. Arredato in stile rustico toscano e dotato di ogni comfort.",
    ],
    [
        'name' => "Casa con Giardino",
        'price' => 100,
        'rooms' => 2,
        'beds' => 4,
        'bathrooms' => 1,
        'square_meters' => 50,
        'address' => "via Cavour 25, 20121, Milano",
        'thumb' => "https://www.savastaimmobiliare.it/wp-content/uploads/2021/06/16-6-Articolo.png",
        'description' => "Appartamento luminoso e spazioso nel cuore di Milano, a pochi passi dalla stazione centrale e dalle principali attrazioni turistiche. L'appartamento è dotato di una camera da letto matrimoniale, un soggiorno con divano letto, una cucina completamente attrezzata e un bagno. È perfetto per coppie o famiglie che desiderano vivere l'esperienza milanese a pieno.",

    ],

    [
        'name' => "Casa Verde",
        'price' => 80,
        'rooms' => 1,
        'beds' => 2,
        'bathrooms' => 1,
        'square_meters' => 35,
        'address' => "via del Corso 10, 00187, Roma",
        'thumb' => "https://www.arredamento.it/img/452/arredare-un-mini-appartamento_oit_381839.webp",
        'description' => "Grazioso monolocale nel cuore di Roma, a due passi da Piazza del Popolo e da tutti i principali luoghi di interesse della città. L'appartamento è dotato di un letto matrimoniale, un angolo cottura completamente attrezzato e un bagno con doccia. È perfetto per coppie o viaggiatori solitari che desiderano vivere l'esperienza romana a pieno.",

    ],

    [
        'name' => "Il Castello",
        'price' => 110,
        'rooms' => 3,
        'beds' => 6,
        'bathrooms' => 2,
        'square_meters' => 80,
        'address' => "via Garibaldi 10, 95121, Catania",
        'thumb' => "https://www.lapassionediarredare.it/wp-content/uploads/2022/11/Come-arredare-con-i-mobili-sospesi-50-idee-25.jpg",
        'description' => "Luminoso e moderno appartamento nel centro storico di Catania, a pochi passi dal Duomo e dal Castello Ursino. L'appartamento è composto da tre camere da letto, un soggiorno con divano letto, una cucina completamente attrezzata e due bagni. È perfetto per gruppi di amici o famiglie che desiderano vivere l'esperienza catanese a pieno.",

    ],
    [
        'name' => "Appartamento Romantico",
        'price' => 55,
        'rooms' => 2,
        'beds' => 3,
        'bathrooms' => 1,
        'square_meters' => 50,
        'address' => "Via delle Carrozze, 00187, Roma",
        'thumb' => "https://www.agriturismohegemone.it/assets/images/apartments/romantico/001gallery/006-appartamento-romantico.jpg",
        'description' => "Elegante appartamento nel cuore di Roma, a pochi passi dalla Fontana di Trevi e dal Pantheon. Dispone di una camera da letto matrimoniale, una cucina completamente attrezzata, un bagno e un soggiorno con divano letto. Wi-Fi gratuito.",

    ],
    [
        'name' => "Casa dei Fiori",
        'price' => 90,
        'rooms' => 3,
        'beds' => 4,
        'bathrooms' => 2,
        'square_meters' => 70,
        'address' => "Piazza della Signoria, 50122, Firenze",
        'thumb' => "https://la-casa-dei-fiori-assisi.hotelmix.it/data/Photos/OriginalPhoto/11190/1119038/1119038802/La-Casa-Dei-Fiori-Villa-Assisi-Exterior.JPEG",
        'description' => "Splendido appartamento nel cuore di Firenze, a due passi dalla famosa Piazza della Signoria. L'appartamento dispone di due camere da letto matrimoniali, due bagni, una cucina completamente attrezzata e un ampio soggiorno. Wi-Fi gratuito.",

    ],
    [
        'name' => "La Mansarda",
        'price' => 75,
        'rooms' => 1,
        'beds' => 2,
        'bathrooms' => 1,
        'square_meters' => 35,
        'address' => "Via Nazionale, 00184, Roma",
        'thumb' => "https://villacellaia.com/wp-content/uploads/2019/06/MANSARDA2.jpg",
        'description' => "Accogliente monolocale nel cuore di Roma, a pochi passi dal Colosseo e dal Foro Romano. Dispone di una camera da letto con letto matrimoniale, una cucina completamente attrezzata e un bagno. Wi-Fi gratuito.",

    ],
    [
        'name' => "Villa con Vista",
        'price' => 130,
        'rooms' => 2,
        'beds' => 4,
        'bathrooms' => 2,
        'square_meters' => 80,
        'address' => "Via Roma, 20122, Milano",
        'thumb' => "https://www.donnamoderna.com/content/uploads/2021/09/errori-da-evitare-in-una-casa-stretta-830x625.jpg",
        'description' => "Elegante appartamento nel cuore di Milano, a pochi passi dal Duomo. Dispone di due camere da letto matrimoniali, due bagni, una cucina completamente attrezzata e un ampio soggiorno con vista sulla citta. Wi-Fi gratuito.",

    ],
    [
        'name' => "Casa con Piscina",
        'price' => 85,
        'rooms' => 3,
        'beds' => 4,
        'bathrooms' => 2,
        'square_meters' => 40,
        'address' => "Via della Scala 30, 00153, Roma",
        'thumb' => "https://www.wowhomes.ch/it/affitti/fotos/2/1626183119e3dadc9f8b71896b3b09cb8a70a1d0eb/162618312107dcb2e74f56de048b5e3cdd6edb582b.jpg",
        'description' => "Luminoso appartamento di 80 mq, situato al 2° piano di un edificio antico, in posizione centralissima nel caratteristico quartiere di Trastevere. L'appartamento è composto da soggiorno con divano letto, cucina attrezzata, due camere da letto matrimoniali, due bagni (uno con vasca e uno con doccia) e una terrazza panoramica con vista sui tetti di Roma.",

    ],
    [
        'name' => "Casa di Campagna",
        'price' => 110,
        'rooms' => 2,
        'beds' => 4,
        'bathrooms' => 2,
        'square_meters' => 50,
        'address' => "Via de' Tornabuoni, 50123, Firenze",
        'thumb' => "https://images.homify.com/c_fill,f_auto,q_0,w_740/v1445165453/p/photo/image/1016443/01.jpg",
        'description' => "Elegante appartamento di 100 mq nel cuore del centro storico di Firenze, situato al 3° piano di un palazzo storico. L'appartamento è composto da soggiorno con divano letto, cucina attrezzata, due camere da letto matrimoniali, due bagni (uno con vasca e uno con doccia) e una terrazza con vista sui monumenti della città.",

    ],
    [
        'name' => "Il Balcone",
        'price' => 70,
        'rooms' => 1,
        'beds' => 2,
        'bathrooms' => 1,
        'square_meters' => 25,
        'address' => "Via San Gregorio Armeno, 80138, Napoli",
        'thumb' => "https://st.hzcdn.com/simgs/a2b13981058a92b6_4-5012/contemporaneo-soggiorno.jpg",
        'description' => "Accogliente monolocale di 30 mq nel cuore del centro storico di Napoli, a pochi passi dalle principali attrazioni turistiche. L'appartamento è composto da una zona giorno con letto matrimoniale, angolo cottura e bagno con doccia. Ideale per una coppia in vacanza nella città partenopea.",

    ],
    [
        'name' => "Appartamento sul Lago",
        'price' => 110,
        'rooms' => 3,
        'beds' => 4,
        'bathrooms' => 2,
        'square_meters' => 80,
        'address' => "Via Monte Grappa 10, 00195, Roma",
        'thumb' => "https://www.villedasogno.net/wp-content/uploads/2019/03/04/Vendita-casa-Lago-di-Garda-a-Padenghe-sul-Garda_01.jpg",
        'description' => "Appartamento elegante e luminoso nel quartiere Prati, a pochi passi dalla Basilica di San Pietro e dai Musei Vaticani. Composto da soggiorno, cucina attrezzata, due camere da letto, due bagni e balcone. Aria condizionata, riscaldamento autonomo e connessione Wi-Fi gratuita.",

    ],
    [
        'name' => "Casa sulle Colline",
        'price' => 80,
        'rooms' => 2,
        'beds' => 4,
        'bathrooms' => 1,
        'square_meters' => 50,
        'address' => "Via Carlo Alberto 13, 20123, Milano",
        'thumb' => "https://www.lapassionediarredare.it/wp-content/uploads/2022/11/Mobile-tv-moderno-50-idee-da-cui-trarre-spunto-17.jpg",
        'description' => "Appartamento raffinato nel cuore di Milano, a pochi passi dal Duomo e dalla Galleria Vittorio Emanuele II. Composto da soggiorno con angolo cottura, camera da letto, bagno e balcone con vista sulla cittÃ . Riscaldamento autonomo e connessione Wi-Fi gratuita.",

    ],
    [
        'name' => "Villa di Lusso",
        'price' => 120,
        'rooms' => 4,
        'beds' => 6,
        'bathrooms' => 2,
        'square_meters' => 100,
        'address' => "Via del Colosseo 12, 00184, Roma",
        'thumb' => "https://www.lapassionediarredare.it/wp-content/uploads/2022/11/Mobile-tv-moderno-50-idee-da-cui-trarre-spunto-19.jpg",
        'description' => "Appartamento spazioso e luminoso a due passi dal Colosseo, nel cuore di Roma. Composto da soggiorno, cucina abitabile, tre camere da letto, due bagni e balcone con vista sul Colosseo. Aria condizionata, riscaldamento autonomo e connessione Wi-Fi gratuita.",

    ],
    [
        'name' => "Casa Chic",
        'price' => 85,
        'rooms' => 2,
        'beds' => 4,
        'bathrooms' => 1,
        'square_meters' => 40,
        'address' => "Via Vittorio Emanuele II, 73100, Lecce LE",
        'thumb' => "https://www.lapassionediarredare.it/wp-content/uploads/2020/12/Appartamento-di-100-mq-4.jpg",
        'description' => "Accogliente appartamento nel centro storico di Lecce, a pochi passi dalle principali attrazioni turistiche, bar e ristoranti. L'appartamento è composto da soggiorno con cucina attrezzata, camera matrimoniale e bagno con doccia. Arredato con gusto e dotato di tutti i comfort, incluso Wi-Fi gratuito e aria condizionata. Perfetto per coppie o famiglie con bambini.",

    ],
    [
        'name' => "Il Soffitto a Volta",
        'price' => 100,
        'rooms' => 3,
        'beds' => 6,
        'bathrooms' => 2,
        'square_meters' => 80,
        'address' => "Via A. De Gasperi, 95121, Catania CT",
        'thumb' => "https://www.lapassionediarredare.it/wp-content/uploads/2022/11/Mobile-tv-moderno-50-idee-da-cui-trarre-spunto-24.jpg",
        'description' => "Ampio appartamento a pochi passi dal centro storico di Catania e dalla stazione centrale. L'appartamento è composto da un ampio soggiorno con divano-letto, cucina attrezzata, tre camere da letto e due bagni. Arredato con gusto e dotato di tutti i comfort, incluso Wi-Fi gratuito e aria condizionata. Perfetto per famiglie o gruppi di amici che vogliono esplorare la splendida città di Catania.",

    ],
    [
        'name' => "Casa degli Amici",
        'price' => 80,
        'rooms' => 2,
        'beds' => 4,
        'bathrooms' => 1,
        'square_meters' => 30,
        'address' => "Vicolo Sant'Agostino 45, 70122, Bari BA",
        'thumb' => "https://images.homify.com/c_fill,f_auto,q_0,w_740/v1438689614/p/photo/image/367149/1.jpg",
        'description' => "Delizioso appartamento completamente ristrutturato nel cuore del centro storico di Bari. A pochi passi dal mare e dal Teatro Petruzzelli. L'appartamento è dotato di tutti i comfort: wifi, aria condizionata, cucina attrezzata, bagno con doccia, phon, ferro da stiro, lavatrice, TV a schermo piatto. Può ospitare fino a 4 persone. "
    ],
    [
        'name' => "Appartamento di Design",
        'price' => 60,
        'rooms' => 2,
        'beds' => 4,
        'bathrooms' => 1,
        'square_meters' => 25,
        'address' => "Via Isabella D'Aragona, 73014, Gallipoli LE",
        'thumb' => "https://www.lapassionediarredare.it/wp-content/uploads/2022/11/Mobile-tv-moderno-50-idee-da-cui-trarre-spunto-22.jpg",
        'description' => "Appartamento appena ristrutturato a 2 passi dal mare e dal centro di Gallipoli. Composto da cucina, soggiorno con divano letto, camera da letto matrimoniale e bagno con doccia. Dotato di aria condizionata, TV, lavatrice e cucina attrezzata. Ideale per una coppia o una famiglia con 2 bambini."
    ],
    [
        'name' => "Casa dei Ricordi",
        'price' => 85,
        'rooms' => 3,
        'beds' => 5,
        'bathrooms' => 2,
        'square_meters' => 40,
        'address' => "Corso Giuseppe Garibaldi, 89125, Reggio Calabria RC",
        'thumb' => "https://www.lapassionediarredare.it/wp-content/uploads/2022/11/Mobile-tv-moderno-50-idee-da-cui-trarre-spunto-5.jpg",
        'description' => "Appartamento luminoso e spazioso nel centro di Reggio Calabria. A pochi minuti a piedi dal Museo Archeologico Nazionale e dal lungomare. L'appartamento è dotato di 3 camere da letto, 2 bagni, cucina attrezzata, salotto con TV e balcone. Connessione Wi-Fi gratuita disponibile in tutta la struttura."
    ],
];
